import './globals.css';

export const metadata = {
  title: 'My Next.js Site',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}


